### ISSUE TITLE
Question about implementation of Conditional Instance Normalization

### ISSUE THREAD

**Issue by vinsis** [MingtaoGuo/Conditional-Instance-Norm-for-n-Style-Transfer#1]
Hi @MingtaoGuo, can you please elaborate on why you do multiply `y1` with `beta` and `gamma` while calculating the `beta` and `gamma` values in [this](https://github.com/MingtaoGuo/Conditional-Instance-Norm-for-n-Style-Transfer/blob/master/ops.py#L5) function? Thanks.

**Comment by MingtaoGuo** [comment]
Hi @vinsis, Thank you for your proposed issue.

Because different (beta and gamma) can represent different style. In [this function](https://github.com/MingtaoGuo/Conditional-Instance-Norm-for-n-Style-Transfer/blob/master/ops.py#L5), the shape of [beta](https://github.com/MingtaoGuo/Conditional-Instance-Norm-for-n-Style-Transfer/blob/05efb4cf86ba65b292bd0757281ca9ed1daa6e44/ops.py#L11) and [gamma](https://github.com/MingtaoGuo/Conditional-Instance-Norm-for-n-Style-Transfer/blob/05efb4cf86ba65b292bd0757281ca9ed1daa6e44/ops.py#L12) is [nums_style, nums_in], which is different from conventional instance norm ([1, nums_in]). 

In views of this, y1 and y2 (one hot type, [1, nums_style]) is used to select the style (multiply y1 with beta [1, nums_style] x [nums_style, nums_in])

Sorry for my poor English. If you still have any questions or need me to explain anything, please ask.

                                                                                      Best regards

**Comment by vinsis** [comment]
Ah, got it. Thank you for replying.
